name: Build APK
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: |
          npm install
          npm install --save-dev @capacitor/core @capacitor/cli @capacitor/android
      - name: Build Web
        run: npm run build
      - name: Sync and Build
        run: |
          npx cap sync
          cd android
          ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/*.apk
          
